name: AppEngine Pull Request

on:
  pull_request:
    paths:
      - 'appengine/**'
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "TEST"
